export const SENTIMENT_CHANGED = "SENTIMENT_CHANGED";
export const CONFIDENCE_CHANGED = "CONFIDENCE_CHANGED";
export const SCORE_CHANGED = "SCORE_CHANGED";
export const SUBJECTIVITY_CHANGED = "SUBJECTIVITY_CHANGED";
export const EMOTIONS_CHANGED = "EMOTIONS_CHANGED";

export const TEXT_AREA_CHANGED = "TEXT_AREA_CHANGED";

export const LOADED = "LOADED";